version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_ORIGINS=http://localhost:80, http://localhost:5173
      - PORT=5000
    volumes:
      - server_uploads:/app/uploads

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  server_uploads:
